import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const outputPath = path.join(rootDir, 'src', 'js', 'stats-data.js');

const USERNAME = 'Epitome87';
const GITHUB_API_URL = `https://github-contributions-api.jogruber.de/v4/${USERNAME}`;
const LEETCODE_API_URL = `https://leetcode-stats-api.herokuapp.com/${USERNAME}`;

async function fetchWithTimeout(url, options = {}, timeoutMs = 12000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...options, signal: controller.signal });
    clearTimeout(timer);
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);
    return await res.json();
  } catch (err) {
    clearTimeout(timer);
    throw err;
  }
}

async function main() {
  console.log('Fetching live stats snapshot for Epitome87...');

  let leetcodeData = null;
  let githubData = null;

  try {
    console.log('Fetching LeetCode stats...');
    leetcodeData = await fetchWithTimeout(LEETCODE_API_URL);
    console.log(`LeetCode fetched successfully (${leetcodeData.totalSolved} solved).`);
  } catch (err) {
    console.warn('Failed to fetch live LeetCode stats:', err.message);
  }

  try {
    console.log('Fetching GitHub contribution data...');
    githubData = await fetchWithTimeout(GITHUB_API_URL);
    console.log(
      `GitHub data fetched successfully (${githubData.total ? Object.keys(githubData.total).length : 0} years).`,
    );
  } catch (err) {
    console.warn('Failed to fetch live GitHub stats:', err.message);
  }

  if (!leetcodeData && !githubData) {
    console.error(
      'Error: Could not fetch LeetCode or GitHub data. Aborting snapshot update to preserve existing data.',
    );
    process.exit(1);
  }

  let existingStats = {};
  try {
    const imported = await import(`file://${outputPath.replace(/\\/g, '/')}?t=${Date.now()}`);
    existingStats = imported;
  } catch {}

  const finalLeetCode = leetcodeData || existingStats.LEETCODE_SNAPSHOT;
  const finalGithubLast =
    githubData && githubData.contributions
      ? githubData.contributions.slice(-365)
      : existingStats.GITHUB_LAST_SNAPSHOT || [];
  const finalGithubAll = githubData && githubData.contributions ? githubData : existingStats.GITHUB_SNAPSHOT || {};

  const fileContent = `/* Generated by scripts/fetch-stats.mjs - Build pre-baked snapshot */
export const LEETCODE_SNAPSHOT = ${JSON.stringify(finalLeetCode, null, 2)};

export const GITHUB_LAST_SNAPSHOT = ${JSON.stringify(finalGithubLast, null, 2)};

export const GITHUB_SNAPSHOT = ${JSON.stringify(finalGithubAll, null, 2)};
`;

  await writeFile(outputPath, fileContent, 'utf8');
  console.log('Successfully written fresh snapshot data to stats-data.js');
}

main().catch((err) => {
  console.error('Fatal error in fetch-stats:', err);
  process.exit(1);
});
